apiVersion: v1
kind: Service
metadata:
  name: raeburn-brain
spec:
  selector:
    app: raeburn-brain
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
