apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: raeburn-brain
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: raeburn-brain
  endpoints:
    - port: metrics
      interval: 30s
