apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: raeburn-brain
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - raeburn.example.com
      secretName: raeburn-brain-tls
  rules:
    - host: raeburn.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: raeburn-brain
                port:
                  number: 80
