apiVersion: v1
kind: Secret
metadata:
  name: raeburn-brain-env
type: Opaque
stringData:
  RAEBURN_DASHBOARD_TOKEN: change-me
  RAEBURN_DATABASE_URL: sqlite:///raeburn.db
  RAEBURN_OAUTH_USER: admin
  RAEBURN_OAUTH_PASS: password
  RAEBURN_CONFIG_SECRET: changeme
  RAEBURN_CONFIG_SIGNATURE: abcdef
