apiVersion: v1
kind: Secret
metadata:
  name: raeburn-brain-env
type: Opaque
stringData:
  RAEBURN_DASHBOARD_TOKEN: {{ .Values.secret.dashboardToken }}
  RAEBURN_DATABASE_URL: {{ .Values.secret.databaseUrl }}
  RAEBURN_OAUTH_USER: {{ .Values.secret.oauthUser }}
  RAEBURN_OAUTH_PASS: {{ .Values.secret.oauthPass }}
  RAEBURN_CONFIG_SECRET: {{ .Values.secret.configSecret }}
  RAEBURN_CONFIG_SIGNATURE: {{ .Values.secret.configSignature }}
